version: "3.8"

services:
  users_tasks_api:
    container_name: "users_tasks_api"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=users_tasks
      - POSTGRES_PASSWORD=users_tasks
      - POSTGRES_DB=users_tasks
  db:
    container_name: "db_users_tasks"
    image: "postgres:16.2-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "users_tasks"
      POSTGRES_PASSWORD: "users_tasks"
      POSTGRES_DB: "users_tasks"
